language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
    - LARAVEL_VERSION=^5.0
    - LARAVEL_VERSION=^6.0
    - LARAVEL_VERSION=^7.0
    - LARAVEL_VERSION=^8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
